// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVuG5GkRGoFB7Oc7Vj01i0p9LqWve9i4',
    appId: '1:637180795054:web:cb58feb1d5fe409fc3353f',
    messagingSenderId: '637180795054',
    projectId: 'first-app-c0009',
    authDomain: 'first-app-c0009.firebaseapp.com',
    databaseURL: 'https://first-app-c0009-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c0009.appspot.com',
    measurementId: 'G-4VTF1VLY05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNhcd-OQ5OSfSd52Scv4zGZDb7jRSd44',
    appId: '1:637180795054:android:0b5b0a1ab1f1a3d2c3353f',
    messagingSenderId: '637180795054',
    projectId: 'first-app-c0009',
    databaseURL: 'https://first-app-c0009-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c0009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBbbxw_RbuvknlhcB7HA5W9Drf5Gkg1I',
    appId: '1:637180795054:ios:c4fa2e90b644b493c3353f',
    messagingSenderId: '637180795054',
    projectId: 'first-app-c0009',
    databaseURL: 'https://first-app-c0009-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c0009.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBbbxw_RbuvknlhcB7HA5W9Drf5Gkg1I',
    appId: '1:637180795054:ios:81d44c3bfd3b29f4c3353f',
    messagingSenderId: '637180795054',
    projectId: 'first-app-c0009',
    databaseURL: 'https://first-app-c0009-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c0009.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
